### ISSUE TITLE
Clerk: auth() was called but it looks like you aren't using `authMiddleware` in your middleware file. Please use `authMiddleware` and make sure your middleware matcher is configured correctly and it matches this route or page.

### ISSUE THREAD

**Issue by Synonymous64** [AntonioErdeljac/next13-ecommerce-admin#2]
### Hello Antonico! I am highly grateful for this project, trying to get my hands on next.js. Your content is excellent.

Actually I am facing problem while making POST request through axios at this point of your [video](https://youtu.be/5miHyP6lExg?t=6070).

I am struggling to solve this error from hours even after checking and following your code and file structure accurately,

![Screenshot from 2023-07-04 00-51-16](https://github.com/AntonioErdeljac/next13-ecommerce-admin/assets/85348583/2985c122-5611-47ba-af63-06e83b26b4d2)

Axios Error:
![Screenshot from 2023-07-04 00-50-59](https://github.com/AntonioErdeljac/next13-ecommerce-admin/assets/85348583/cb907752-0134-4881-9547-6d9c37252517)

Mine File Structure:
![Screenshot from 2023-07-04 01-08-49](https://github.com/AntonioErdeljac/next13-ecommerce-admin/assets/85348583/d8f48139-9a13-494b-81fb-8dbc40c630a7)

**Comment by poe10** [comment]
just move out file middleware.ts from public folder

**Comment by navi-05** [comment]
Make sure you've default exported authMiddleware() function from @clerk/nextjs in middleware.ts file

**Comment by Eclarkhalid** [comment]
I got the same error too, make sure after writing the layout for the dashboard, you don't have your app running. Make sure you delete the .next folder before running the app again

**Comment by Yair-N** [comment]
Had the same issue, make sure to complete the app setup on clerk.
The way to see if your clerk account and authentication service for your app are in sync is to
 logout | clean data for localhost on your browser
 restart app and a new browser session 
 and sign in to your admin dashboard. 

If everything is ok, you should be redirected to the dashboard after signing in.
For me it actually redirected in to clerk asking to "build my application" or something similar.
(i think there was a prompt with 'clerk cannot redirect to any app because setup is not complete' )
 after clicking that I finalized the setup and actually connected the app to the authentication process.
Can't remember exactly what was the process

If this is the case maybe there's a step we missed on setting it up in the first place.

**Comment by viethoang7276** [comment]
I have the same problem, any fix for it yet?

**Comment by CVE-2002-1215** [comment]
Hi Everyone if you gets this error for Antonio Project which is "Full Stack E-Commerce + Dashboard & CMS: Next.js 13 App Router, React, Tailwind, Prisma, MySQL, 2023". I got the same issue. The problem is my typing fault. Check whether you made same fault , if yes fix the code then try to run project. Problem was in this file /components/modals/store-modal.tsx.

![Screenshot 2023-08-11 at 19 04 57](https://github.com/AntonioErdeljac/next13-ecommerce-admin/assets/112773193/a685af56-997b-4d31-872e-f74b17c004b3)
![Screenshot 2023-08-11 at 19 06 23](https://github.com/AntonioErdeljac/next13-ecommerce-admin/assets/112773193/a103cfe3-87c6-4c1c-ab43-83ab1c3d2536)

You should be using backticks ` `  in this part.

**Comment by aksh978** [comment]
Just change the code in middleware.ts from 

```
export default authMiddleware({
  publicRoutes : ["/api", "/api/:path*"],
});
```
to
```
export default authMiddleware({
  ignoredRoutes: ["/api", "/api/:path*"],
});
```

that will run the application

**Comment by Synonymous64** [comment]
I just had to delete the. next and node modules and re execute the project
Everything worked perfectly.
